require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true

Lint/AmbiguousOperator:
  Enabled: true
  Exclude:
    - test/**/*.rb

Lint/BigDecimalNew:
  Enabled: true

Lint/BooleanSymbol:
  Enabled: true

Lint/CircularArgumentReference:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/DuplicateHashKey:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/FlipFlop:
  Enabled: true

Lint/FloatOutOfRange:
  Enabled: true

Lint/FormatParameterMismatch:
  Enabled: true

Lint/HeredocMethodCallPosition:
  Enabled: true

Lint/ImplicitStringConcatenation:
  Enabled: true

Lint/LiteralAsCondition:
  Enabled: true

Lint/RescueException:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Performance/FlatMap:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Rails/ActionFilter:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/Validation:
  Enabled: true

Rails/ActiveRecordAliases:
  Enabled: true

Rails/ActiveSupportAliases:
  Enabled: true

Rails/ActiveRecordOverride:
  Enabled: true

Rails/AssertNot:
  Enabled: true

Rails/DynamicFindBy:
  Enabled: true
  Exclude:
    - 'test/system/**/*'

Rails/Presence:
  Enabled: true

Rails/ReflectionClassName:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

Rails/RedundantAllowNil:
  Enabled: true

Rails/RedundantReceiverInWithOptions:
  Enabled: true

Rails/FindBy:
  Enabled: true
  Include:
    - app/**/*.rb

Rails/EnvironmentComparison:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: true

Rails/HttpStatus:
  Enabled: true

Security/Eval:
  Enabled: true

Security/JSONLoad:
  Enabled: true

Security/MarshalLoad:
  Enabled: true

Security/Open:
  Enabled: true

Security/YAMLLoad:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/EvenOdd:
  Enabled: true

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Style/NegatedUnless:
  Enabled: true

Style/NegatedIf:
  Enabled: true
  EnforcedStyle: postfix

Style/NegatedWhile:
  Enabled: true

Style/NilComparison:
  Enabled: true

Style/NonNilCheck:
  Enabled: true
